

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useRoutes, RouteObject } from 'react-router-dom';
import { Homepage } from '@/modules/main/pages/Homepage';

export const AppRoutes = () => {
  const routes: RouteObject[] = [
    { path: '/', element: <Homepage /> }
  ];

  const element = useRoutes(routes);

  return <>{element}</>;
};
