

/**
* Generated by ExoCoding 0.0.1
*/

import React from 'react';
import { useRoutes, RouteObject } from 'react-router-dom';

export const AppRoutes = () => {
  const routes: RouteObject[] = [
  ];

  const element = useRoutes(routes);

  return <>{element}</>;
};
