

/**
* Generated by ExoCoding 0.0.1
*/

import { AxiosRequestConfig } from 'axios';
import { axios } from '@/lib/axios';
import { Page } from '@/types';

/**
* Create one Table1Obj
*
* @param {body} CRUD input parameter
* @param {options} Override http request option. */
export const postTable1Obj = (body: any, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.post(`/Table1Obj`, body, options);
};

/**
* Delete one Table1Obj
*
* @param {idTable1} CRUD key input parameter
* @param {options} Override http request option.
* @returns Table1Obj */
export const deleteTable1Obj = (idTable1:  number, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.delete(`/Table1Obj/${idTable1}`, options);
};

/**
* Read a list of Table1Obj
*
* @param {options} Override http request option.
* @returns Table1Obj */
export const getTable1ObjList = (options: AxiosRequestConfig = {}): Promise<any[]> => {
    return axios.get(`/Table1Obj`, options);
};

/**
* Update one Table1Obj
*
* @param {idTable1} CRUD key input parameter
* @param {body} CRUD input parameter
* @param {options} Override http request option.
* @returns Table1Obj */
export const putTable1Obj = (idTable1:  number, body: any, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.put(`/Table1Obj/${idTable1}`, body, options);
};

/**
* Read one Table1Obj
*
* @param {idTable1} CRUD key input parameter
* @param {options} Override http request option.
* @returns Table1Obj */
export const getTable1Obj = (idTable1:  number, options: AxiosRequestConfig = {}): Promise<any> => {
    return axios.get(`/Table1Obj/${idTable1}`, options);
};
