package com.artsoft.abc;

import javax.annotation.processing.Generated;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@Generated(value = "com.exocode.codegen", comments = "Generated by ExoCoding 0.0.1-SNAPSHOT")
@SpringBootTest
class MainTests {

	@Test
	void contextLoads() {
	}

}
