

/**
* Generated by ExoCoding 0.0.1
*/

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

import translationEN from '@/lib/locales/en.json';
import translationAK from '@/lib/locales/ak.json';

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        fallbackLng: 'en',
        resources: {
            en: { translation: translationEN }
            ak: { translation: translationAK }
        }
    });
